#!/bin/bash
fName=$1
objfile=$fName.o
sourcefile=$fName.s
executable=$fName

if [ -f "./$objfile" ]; then
echo "Preserving previous compiles"
mv ./$executable $executable.bak
as -gstabbs -o $objfile $sourcefile
ld -o $executable $objfile
echo "Compile complete"
else
as -gstabbs -o $objfile $sourcefile
ld -o $executable $objfile
echo "Compile Complete"
fi
